spring:
  config:
   activate:
    on-profile: local
  # 공통 ANSI 컬러 로그 설정
  output:
    ansi:
      enabled: ALWAYS

#--- 공통 설정 과 로컬 및 서버 설정 분리 전 설정 ---
#spring:
#  application:
#    name: study
#
#  h2:
#    console:
#      enabled: true
#      path: /h2
#
#      # EC2 에서 서버를 구동시켰을때 h2 를 접근하기 위한 방법
#      settings:
#        web-allow-others: true
#
#  datasource:
#
#    # h2 console 에서 url 부분을 똑같이 맞춰줘야 함
#    url: jdbc:h2:mem:test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ''
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        highlight_sql: true
#        color-codes: true
#        use_sql_comments: true
#    defer-datasource-initialization: true
#
#  # 콘솔에서 info 같은 로그 색 입혀주는 설정
#  output:
#    ansi:
#      enabled: ALWAYS
#
##  security:
##    user:
##      name: user
##      password: 1234
